Add new examples for floating-js-api and the embedded component
unblu/visitor-js-api-example pull request #24
Opened 2023-10-16 09:22 UTC by davideberlein

- rewrote all examples for the visitors-js-api which is now called the floating-js-api using npm as dependency
- added angular, react and global examples for the embedded app component

2023-10-16 14:55 UTC, truebden approved these changes

2023-10-16 14:55 UTC, truebden commented on README.md
there is now no root readme file anymore, but I would keep one

2023-10-16 14:55 UTC, truebden commented on embedded-app-component/angular/.vscode/extensions.json
should we keep the files in .vscode?

2023-10-16 14:55 UTC, truebden commented on floating-js-api/es-module/.idea/vcs.xml
here are also quiet some files from the idea plugins in the project

2023-10-17 09:04 UTC, kadang requested changes

2023-10-17 09:04 UTC, kadang commented on floating-js-api/es-module/README.md
> +- make sure node-js and npm are installed.
```suggestion
- Make sure node-js and npm are installed.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/es-module/README.md
> +- change to the cloned project folder and call `npm install`
```suggestion
- Change to the cloned project folder and call `npm install`.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/es-module/README.md
> +- call `npm run build` to build the project (into the dist folder). The files in the dist folder may be hosted and used on any webserver.
```suggestion
- Call `npm run build` to build the project into the `dist` folder. The files in the `dist` folder may be hosted and used on any web server.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/es-module/README.md
> +- call `npm run dev` to automatically build and host the project on port `8080` using webpack dev server.
```suggestion
- Call `npm run dev` to automatically build and host the project on port `8080` using the webpack dev server.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +This example shows how to integrate the Unblu Floating JS API into a website, loading the bundled file from the Unblu collaboration server (either cloud or on premises installation) and accessing the
```suggestion
This example shows how to integrate the Unblu Floating JS API into a website, loading the bundled file from the Unblu Collaboration Server (either Unblu Cloud or an on-premises installation) and accessing the API via the global `window.unblu.api` space.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +For more information about the Unblu Floating JS API see its [documentation](https://www.unblu.com/en/docs/latest/reference/unblu-visitor-js-api/).
```suggestion
For more information about the Unblu Floating JS API see its [documentation](https://www.unblu.com/en/docs/latest/reference/unblu-floating-js-api/).
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +To make sure you have the latest version, copy the typedefs following the steps in the [global installation guide](https://www.unblu.com/en/docs/latest/reference/unblu-visitor-js-api/#global-scope).
```suggestion
To make sure you have the latest version, copy the typedefs following the steps in the [global installation guide](https://www.unblu.com/en/docs/latest/reference/unblu-floating-js-api/#global-scope).
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +In order to make this example work in your environment some changes have to be done.
```suggestion
You have to make some changes to make this example work in your environment.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +Depending on if you are using the Unblu cloud or an on premises installation chose your use case and follow the steps there:
```suggestion
The changes vary depending on whether you're using the Unblu Cloud or an on-premises installation.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +### Unblu cloud
```suggestion
### Unblu Cloud
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +When running on the Unblu cloud replace the API Key `MZsy5sFESYqU7MawXZgR_w` with your API key which you can find under `Account Management Page -> API Keys`
```suggestion
Replace the API Key `MZsy5sFESYqU7MawXZgR_w` with your API key.
You can find your API key under `Account Management Page -> API Keys`.
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +### On premises
```suggestion
### On-premises
```

2023-10-17 09:04 UTC, kadang commented on floating-js-api/global/README.md
> +To do so first install the dependencies:
```suggestion
To do so, first install the dependencies:
```

2023-10-17 10:01 UTC, davideberlein commented on embedded-app-component/angular/README.md
> +Lastly in our App [component file](./src/app/app.component.ts) we add the fields that will be used of our attributes as
I changed your suggestion to hopefully be clearer

2023-10-17 10:05 UTC, davideberlein commented on embedded-app-component/angular/README.md
> +well as the listener functions and call the API of the `UnbluEmbeddedAppElement` from with Angular's `ngAfterViewInit`
I also updated this one to add more context

2023-10-17 10:07 UTC, davideberlein commented on embedded-app-component/react/README.md
> +As the Unblu Embedded App is built as a WebComponent (a custom `HTMLElement`) which is an unknown component in the React system, we have to let React know that it exists which we do in the [typedef](
I guess so :-D

2023-10-17 10:21 UTC, truebden requested changes
the part with the root readme should be done

2023-10-17 10:26 UTC, davideberlein commented on embedded-app-component/angular/.vscode/extensions.json
angular generates these when it creates the project So I think it might make sense to keep them

2023-10-17 12:09 UTC, kadang requested changes

2023-10-17 12:09 UTC, kadang commented on README.md
> +- [Floating API](./floating-js-api): See how to control the Unblu Floating Visitor UI using JavaScript.
```suggestion
- [Floating JS API](./floating-js-api): See how to control the Unblu Floating Visitor UI using JavaScript.
```
Sorry, I missed that first time round :(

2023-10-17 12:26 UTC, kadang approved these changes

2023-10-17 14:06 UTC, truebden approved these changes

2023-10-18 06:34 UTC, merged